modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://gitea.gildedgames.com/GildedGames/OrbisLib/issues"
logoFile="logo.png"

[[mods]]
modId="orbis-lib"
version="${file.jarVersion}"
displayName="OrbisLib"
displayURL="https://gildedgames.com/"
credits="Designed and developed by Gilded Games with <3. Made possible thanks to our supporters on Patreon, and with special thanks to our project reporters, contributors, and moderation team."
authors="Brandon Pearce, Emile van Krieken, Angeline"
description='''
OrbisLib allows developers to interact and use Orbis data structures.

OrbisLib wouldn't be possible without our supporters on Patreon! Consider supporting development at: https://patreon.com/GildedGames

View the source code and contribute to the Orbis project on our official Gitea here: https://gitea.gildedgames.com/GildedGames/Orbis

We also have an official Discord server! https://aether.gildedgames.com/discord

Running into issues or have a question? Check out our support page here: https://orbis.gildedgames.com/support
'''
